### ISSUE TITLE
Clean up Netlify previews setup

### ISSUE THREAD

**Issue by thibaudcolas** [djangocon/2023.djangocon.eu#21]
Somehow I have created two Netlify projects for the same repository. I’m not entirely sure why, (likely just by mistake). Should investigate, only keep one, and make sure previews still work.

**Comment by sabderemane** [comment]
@thibaudcolas is it still the case ? Only you can see the configuration of Netlify at the moment

**Comment by thibaudcolas** [comment]
@sabderemane yes it’s still the case. Should just be a matter of deleting one project but since it’s only confusing for me I’ve not gotten to it yet.

**Comment by thibaudcolas** [comment]
Fixed today – now using: https://deploy-preview-65--2023-djangocon-eu-previews.netlify.app/
