### ISSUE TITLE
Add an Inclusivity section

### ISSUE THREAD

**Issue by rebkwok** [djangocon/2023.djangocon.eu#27]
A page about what we do to promote inclusivity

including:
- STTRs
- creche 
- accessibility info for venue
- quiet room
etc

PyCon UK's page is a good template: https://2022.pyconuk.org/inclusion/

**Comment by sabderemane** [comment]
@rebkwok where will be the page in the menu ?

**Comment by rebkwok** [comment]
Probably the "about" section?
